name: shadow_training
description: A new Flutter project.

version: 1.0.0+10064

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2
  flame: ^0.11.2
  shared_preferences: ^0.5.2
  soundpool: ^0.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.7.0

dependency_overrides:
  image: 2.0.7

flutter:
  uses-material-design: true
  assets:
    - assets/audio/bgm.ogg
    - assets/audio/swish-1.ogg
    - assets/audio/swish-2.ogg
    - assets/audio/swish-3.ogg
    - assets/audio/swish-4.ogg
    - assets/audio/swish-5.ogg
    - assets/audio/swish-6.ogg
    - assets/audio/swish-7.ogg
    - assets/audio/swish-8.ogg
    - assets/audio/swish-9.ogg
    - assets/audio/swish-10.ogg
    - assets/audio/swish-11.ogg
    - assets/audio/swish-12.ogg
    - assets/audio/swish-13.ogg
    - assets/images/background.png
    - assets/images/boxer/dizzy.png
    - assets/images/boxer/idle.png
    - assets/images/boxer/punch-left.png
    - assets/images/boxer/punch-right.png
    - assets/images/boxer/punch-up.png
    - assets/images/markers.png
    - assets/images/perfect-time.png
    - assets/images/title.png

  fonts:
    - family: HVD
      fonts:
        - asset: fonts/hvd.otf

flutter_icons:
  android: true
  ios: true
  image_path_android: assets/launcher-icon/ic_launcher.png
  image_path_ios: assets/launcher-icon/ic_launcher.png
  adaptive_icon_background: assets/launcher-icon/background-only.png
  adaptive_icon_foreground: assets/launcher-icon/foreground-only.png
