name: shadow_training
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2
  flame: ^0.11.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/background.png
    - assets/images/boxer/dizzy.png
    - assets/images/boxer/idle.png
    - assets/images/boxer/punch-left.png
    - assets/images/boxer/punch-right.png
    - assets/images/boxer/punch-up.png
    - assets/images/markers.png
    - assets/images/perfect-time.png
